version: '3.9'

networks:
  wp_net:
    name: wordpress_net

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: web_https-portal
    ports:
      - ${HOSTNAME_WORDPRESS}:80:80
      - ${HOSTNAME_WORDPRESS}:443:443
    depends_on:
      - nginx
    restart: always
    volumes:
      - ./certs:/var/lib/https-portal
    networks:
      - wp_net
    environment:
      STAGE: 'local'
#      STAGE: 'staging'
#      STAGE: 'production'
      DOMAINS: >-
        ${HOSTNAME_WORDPRESS} -> http://nginx
      WORKER_PROCESSES: auto
      WORKER_CONNECTIONS: 2048
      CLIENT_MAX_BODY_SIZE: '128M'

  # Nginx
  nginx:
    image: nginx:stable
    container_name: web_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
    networks:
      - wp_net
    depends_on:
      - wordpress
    restart: always

  # WordPress+PHP7.4
  wordpress:
    #image: wordpress:php7.4-apache
    build: ./image/
    container_name: web_wordpress
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress-php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wp_net
    depends_on:
      - mysql
    restart: always

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: web_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wp_net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
